language: go

go:
  - 1.6
  - tip

install:
  - go get github.com/go-telegram-bot-api/telegram-bot-api
  - go get github.com/bitly/go-simplejson

script:
  - go test -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
